// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#ifndef _AMOLED_UI_H
#define _AMOLED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_The_A.h"
#include "ui_The_B.h"
#include "ui_The_C.h"
#include "ui_The_D.h"
#include "ui_The_E.h"
#include "ui_The_F.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * FADEON_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MOVEY_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MOVEFY_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_TIME4);
LV_FONT_DECLARE(ui_font_TIME4_2);
LV_FONT_DECLARE(lv_font_simsun_16_cjk);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
