// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#include "ui.h"

typedef enum {
    UI_THE_B_ICON_SYMBOL = 0,
    UI_THE_B_ICON_STEP,
    UI_THE_B_ICON_WEATHER,
    UI_THE_B_ICON_HEART,
    UI_THE_B_ICON_NEWS,
    UI_THE_B_ICON_MUSIC,
    UI_THE_B_ICON_NOTE,
    UI_THE_B_ICON_CALC,
    UI_THE_B_ICON_COMPASS,
    UI_THE_B_ICON_SETTING,
    UI_THE_B_ICON_CLOCK,
} ui_the_b_icon_kind_t;

static const lv_point_t ui_the_b_heart_wave_points[] = {
    {0, 16}, {10, 16}, {16, 8}, {22, 24}, {30, 2}, {38, 16}, {50, 16}
};

lv_obj_t * ui_The_B = NULL;
lv_obj_t * ui_Mune = NULL;
lv_obj_t * ui_Step = NULL;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_Music = NULL;
lv_obj_t * ui_Notebook = NULL;
lv_obj_t * ui_Caculator = NULL;
lv_obj_t * ui_Heart_Detect = NULL;
lv_obj_t * ui_Compass = NULL;
lv_obj_t * ui_SettingApp = NULL;
lv_obj_t * ui_News = NULL;
lv_obj_t * ui_Clock = NULL;

static const lv_coord_t ui_the_b_icon_bg_size_normal = 64;
static const lv_coord_t ui_the_b_icon_bg_size_pressed = 58;
static const uint16_t ui_the_b_anim_ms_press = 80;
static const uint16_t ui_the_b_anim_ms_release = 120;

static void ui_the_b_anim_exec_icon_size(void *var, int32_t v)
{
    lv_obj_t *icon_bg = (lv_obj_t *)var;
    lv_coord_t size = (lv_coord_t)v;
    lv_coord_t offset_y = (ui_the_b_icon_bg_size_normal - size) / 2;

    lv_obj_set_size(icon_bg, size, size);
    lv_obj_align(icon_bg, LV_ALIGN_TOP_MID, 0, offset_y);
}

static void ui_the_b_anim_icon_size_to(lv_obj_t *obj, lv_coord_t size_target, uint16_t duration_ms)
{
    if (obj == NULL) {
        return;
    }

    lv_anim_del(obj, ui_the_b_anim_exec_icon_size);

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, obj);
    lv_anim_set_values(&a, (int32_t)lv_obj_get_width(obj), (int32_t)size_target);
    lv_anim_set_time(&a, duration_ms);
    lv_anim_set_exec_cb(&a, ui_the_b_anim_exec_icon_size);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_start(&a);
}

static void ui_the_b_app_press_effect_event_cb(lv_event_t *e)
{
    const lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *icon_bg = (lv_obj_t *)lv_event_get_user_data(e);

    if (code == LV_EVENT_PRESSED) {
        ui_the_b_anim_icon_size_to(icon_bg, ui_the_b_icon_bg_size_pressed, ui_the_b_anim_ms_press);
    } else if (code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
        ui_the_b_anim_icon_size_to(icon_bg, ui_the_b_icon_bg_size_normal, ui_the_b_anim_ms_release);
    }
}

static lv_obj_t *ui_the_b_create_shape(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h, lv_coord_t radius, lv_color_t color)
{
    lv_obj_t *shape = lv_obj_create(parent);
    lv_obj_set_size(shape, w, h);
    lv_obj_set_pos(shape, x, y);
    lv_obj_clear_flag(shape, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(shape, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_radius(shape, radius, 0);
    lv_obj_set_style_bg_color(shape, color, 0);
    lv_obj_set_style_bg_opa(shape, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(shape, 0, 0);
    lv_obj_set_style_shadow_width(shape, 0, 0);
    lv_obj_set_style_outline_width(shape, 0, 0);
    lv_obj_set_style_pad_all(shape, 0, 0);
    return shape;
}

static void ui_the_b_create_step_icon(lv_obj_t *parent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);

    ui_the_b_create_shape(parent, 10, 24, 14, 24, 7, white);
    ui_the_b_create_shape(parent, 18, 13, 10, 10, 5, white);
    ui_the_b_create_shape(parent, 31, 13, 14, 24, 7, white);
    ui_the_b_create_shape(parent, 39, 36, 10, 10, 5, white);
}

static void ui_the_b_create_weather_icon(lv_obj_t *parent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    lv_color_t sun = lv_color_hex(0xFFD166);

    ui_the_b_create_shape(parent, 10, 10, 18, 18, 9, sun);
    ui_the_b_create_shape(parent, 21, 21, 16, 16, 8, white);
    ui_the_b_create_shape(parent, 10, 25, 20, 20, 10, white);
    ui_the_b_create_shape(parent, 29, 25, 20, 20, 10, white);
    ui_the_b_create_shape(parent, 12, 34, 36, 12, 6, white);
}

static void ui_the_b_create_heart_icon(lv_obj_t *parent)
{
    lv_obj_t *line = lv_line_create(parent);
    lv_line_set_points(line, ui_the_b_heart_wave_points, sizeof(ui_the_b_heart_wave_points) / sizeof(ui_the_b_heart_wave_points[0]));
    lv_obj_set_pos(line, 6, 18);
    lv_obj_clear_flag(line, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_line_width(line, 5, 0);
    lv_obj_set_style_line_color(line, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_line_rounded(line, true, 0);
}

static void ui_the_b_create_news_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_obj_t *paper = ui_the_b_create_shape(parent, 14, 10, 36, 42, 9, lv_color_hex(0xFFFFFF));
    ui_the_b_create_shape(paper, 7, 8, 22, 5, 2, accent);
    ui_the_b_create_shape(paper, 7, 18, 22, 4, 2, accent);
    ui_the_b_create_shape(paper, 7, 27, 16, 4, 2, accent);
    ui_the_b_create_shape(paper, 26, 25, 4, 10, 2, accent);
}

static void ui_the_b_create_music_icon(lv_obj_t *parent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    ui_the_b_create_shape(parent, 19, 10, 6, 28, 3, white);
    ui_the_b_create_shape(parent, 25, 10, 18, 6, 2, white);
    ui_the_b_create_shape(parent, 34, 10, 6, 20, 3, white);
    ui_the_b_create_shape(parent, 13, 34, 14, 14, 7, white);
    ui_the_b_create_shape(parent, 30, 28, 14, 14, 7, white);
}

static void ui_the_b_create_note_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_obj_t *paper = ui_the_b_create_shape(parent, 14, 11, 36, 42, 10, lv_color_hex(0xFFFFFF));
    ui_the_b_create_shape(paper, 8, 10, 20, 4, 2, accent);
    ui_the_b_create_shape(paper, 8, 20, 20, 4, 2, accent);
    ui_the_b_create_shape(paper, 8, 30, 14, 4, 2, accent);
    ui_the_b_create_shape(paper, 24, 28, 4, 10, 2, accent);
}

static void ui_the_b_create_calc_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    lv_obj_t *body = ui_the_b_create_shape(parent, 15, 10, 34, 44, 10, white);
    ui_the_b_create_shape(body, 7, 7, 20, 8, 3, accent);
    ui_the_b_create_shape(body, 7, 21, 7, 7, 2, accent);
    ui_the_b_create_shape(body, 18, 21, 7, 7, 2, accent);
    ui_the_b_create_shape(body, 7, 32, 7, 7, 2, accent);
    ui_the_b_create_shape(body, 18, 32, 7, 7, 2, accent);
}

static void ui_the_b_create_compass_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    ui_the_b_create_shape(parent, 12, 12, 40, 40, 20, white);
    ui_the_b_create_shape(parent, 18, 18, 28, 28, 14, accent);

    static const lv_point_t compass_pts[] = {
        {0, 11}, {11, 0}, {22, 11}, {11, 22}, {0, 11}
    };
    lv_obj_t *needle = lv_line_create(parent);
    lv_line_set_points(needle, compass_pts, sizeof(compass_pts) / sizeof(compass_pts[0]));
    lv_obj_set_pos(needle, 21, 21);
    lv_obj_clear_flag(needle, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_line_width(needle, 3, 0);
    lv_obj_set_style_line_color(needle, white, 0);
    lv_obj_set_style_line_rounded(needle, true, 0);
}

static void ui_the_b_create_setting_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    ui_the_b_create_shape(parent, 11, 25, 42, 14, 7, white);
    ui_the_b_create_shape(parent, 19, 13, 10, 10, 5, white);
    ui_the_b_create_shape(parent, 35, 41, 10, 10, 5, white);
    ui_the_b_create_shape(parent, 25, 20, 14, 14, 7, accent);
}

static void ui_the_b_create_clock_icon(lv_obj_t *parent, lv_color_t accent)
{
    lv_color_t white = lv_color_hex(0xFFFFFF);
    ui_the_b_create_shape(parent, 12, 12, 40, 40, 20, white);
    ui_the_b_create_shape(parent, 17, 17, 30, 30, 15, accent);
    ui_the_b_create_shape(parent, 30, 21, 4, 14, 2, white);
    ui_the_b_create_shape(parent, 30, 31, 10, 4, 2, white);
}

static void ui_the_b_apply_cn_text_style(lv_obj_t *label)
{
    lv_obj_set_style_text_font(label, &lv_font_simsun_16_cjk, 0);
    lv_obj_set_style_transform_zoom(label, 192, 0);
}

static void ui_the_b_create_icon(lv_obj_t *parent, ui_the_b_icon_kind_t icon_kind, const char *symbol, lv_color_t accent)
{
    switch(icon_kind) {
        case UI_THE_B_ICON_STEP:
            ui_the_b_create_step_icon(parent);
            break;
        case UI_THE_B_ICON_WEATHER:
            ui_the_b_create_weather_icon(parent);
            break;
        case UI_THE_B_ICON_HEART:
            ui_the_b_create_heart_icon(parent);
            break;
        case UI_THE_B_ICON_NEWS:
            ui_the_b_create_news_icon(parent, accent);
            break;
        case UI_THE_B_ICON_MUSIC:
            ui_the_b_create_music_icon(parent);
            break;
        case UI_THE_B_ICON_NOTE:
            ui_the_b_create_note_icon(parent, accent);
            break;
        case UI_THE_B_ICON_CALC:
            ui_the_b_create_calc_icon(parent, accent);
            break;
        case UI_THE_B_ICON_COMPASS:
            ui_the_b_create_compass_icon(parent, accent);
            break;
        case UI_THE_B_ICON_SETTING:
            ui_the_b_create_setting_icon(parent, accent);
            break;
        case UI_THE_B_ICON_CLOCK:
            ui_the_b_create_clock_icon(parent, accent);
            break;
        case UI_THE_B_ICON_SYMBOL:
        default: {
            lv_obj_t *icon = lv_label_create(parent);
            lv_label_set_text(icon, symbol);
            lv_obj_center(icon);
            lv_obj_clear_flag(icon, LV_OBJ_FLAG_CLICKABLE);
            lv_obj_set_style_text_font(icon, &lv_font_montserrat_16, 0);
            lv_obj_set_style_text_color(icon, lv_color_hex(0xFFFFFF), 0);
            break;
        }
    }
}

static lv_obj_t *ui_the_b_create_app(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_color_t color,
                                     ui_the_b_icon_kind_t icon_kind, const char *symbol, const char *title)
{
    lv_obj_t *card = lv_obj_create(parent);
    lv_obj_set_size(card, 72, 86);
    lv_obj_set_pos(card, x, y);
    lv_obj_clear_flag(card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(card, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK);
    lv_obj_set_style_radius(card, 24, 0);
    lv_obj_set_style_bg_color(card, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(card, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(card, 0, 0);
    lv_obj_set_style_shadow_width(card, 0, 0);
    lv_obj_set_style_pad_all(card, 0, 0);

    lv_obj_t *icon_bg = lv_obj_create(card);
    lv_obj_set_size(icon_bg, ui_the_b_icon_bg_size_normal, ui_the_b_icon_bg_size_normal);
    lv_obj_align(icon_bg, LV_ALIGN_TOP_MID, 0, 0);
    lv_obj_clear_flag(icon_bg, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(icon_bg, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_radius(icon_bg, 20, 0);
    lv_obj_set_style_bg_color(icon_bg, color, 0);
    lv_obj_set_style_bg_opa(icon_bg, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(icon_bg, 0, 0);
    lv_obj_set_style_shadow_width(icon_bg, 0, 0);
    lv_obj_set_style_pad_all(icon_bg, 0, 0);

    ui_the_b_create_icon(icon_bg, icon_kind, symbol, color);

    lv_obj_t *label = lv_label_create(card);
    lv_label_set_text(label, title);
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_clear_flag(label, LV_OBJ_FLAG_CLICKABLE);
    ui_the_b_apply_cn_text_style(label);
    lv_obj_set_style_text_color(label, lv_color_hex(0xD8DEE9), 0);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, 0);

    lv_obj_add_event_cb(card, ui_the_b_app_press_effect_event_cb, LV_EVENT_PRESSED, icon_bg);
    lv_obj_add_event_cb(card, ui_the_b_app_press_effect_event_cb, LV_EVENT_RELEASED, icon_bg);
    lv_obj_add_event_cb(card, ui_the_b_app_press_effect_event_cb, LV_EVENT_PRESS_LOST, icon_bg);

    return card;
}

void ui_event_The_B(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_get_act();

    if(event_code != LV_EVENT_GESTURE || indev == NULL) {
        return;
    }

    lv_dir_t dir = lv_indev_get_gesture_dir(indev);
    if(dir == LV_DIR_TOP && ui_The_C_is_open()) {
        lv_indev_wait_release(indev);
        ui_The_C_hide();
        return;
    }

    if(ui_The_C_is_open()) {
        return;
    }

    if(dir == LV_DIR_LEFT) {
        lv_indev_wait_release(indev);
        _ui_screen_change(&ui_The_D, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_The_D_screen_init);
    }
    if(dir == LV_DIR_RIGHT) {
        lv_indev_wait_release(indev);
        _ui_screen_change(&ui_The_A, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_The_A_screen_init);
    }
}

void ui_The_B_screen_init(void)
{
    ui_The_B = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_The_B, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_The_B, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_The_B, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mune = lv_obj_create(ui_The_B);
    lv_obj_set_size(ui_Mune, 410, 502);
    lv_obj_align(ui_Mune, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(ui_Mune, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_Mune, 0, 0);
    lv_obj_set_style_bg_color(ui_Mune, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(ui_Mune, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(ui_Mune, 0, 0);
    lv_obj_set_style_pad_all(ui_Mune, 0, 0);

    ui_Step = ui_the_b_create_app(ui_Mune, 24, 112, lv_color_hex(0x08BDBD), UI_THE_B_ICON_STEP, NULL, "步数");
    ui_Weather = ui_the_b_create_app(ui_Mune, 100, 112, lv_color_hex(0x3A86FF), UI_THE_B_ICON_WEATHER, NULL, "天气");
    ui_Music = ui_the_b_create_app(ui_Mune, 176, 112, lv_color_hex(0x8338EC), UI_THE_B_ICON_MUSIC, NULL, "音乐");
    ui_Notebook = ui_the_b_create_app(ui_Mune, 252, 112, lv_color_hex(0xFB5607), UI_THE_B_ICON_NOTE, NULL, "便签");
    ui_Caculator = ui_the_b_create_app(ui_Mune, 328, 112, lv_color_hex(0xFFBE0B), UI_THE_B_ICON_CALC, NULL, "计算");
    ui_Heart_Detect = ui_the_b_create_app(ui_Mune, 24, 246, lv_color_hex(0xE63946), UI_THE_B_ICON_HEART, NULL, "心率");
    ui_Compass = ui_the_b_create_app(ui_Mune, 100, 246, lv_color_hex(0x2A9D8F), UI_THE_B_ICON_COMPASS, NULL, "指南");
    ui_SettingApp = ui_the_b_create_app(ui_Mune, 176, 246, lv_color_hex(0x6C757D), UI_THE_B_ICON_SETTING, NULL, "设置");
    ui_News = ui_the_b_create_app(ui_Mune, 252, 246, lv_color_hex(0x4361EE), UI_THE_B_ICON_NEWS, NULL, "消息");
    ui_Clock = ui_the_b_create_app(ui_Mune, 328, 246, lv_color_hex(0xF72585), UI_THE_B_ICON_CLOCK, NULL, "时钟");

    lv_obj_add_event_cb(ui_The_B, ui_event_The_B, LV_EVENT_ALL, NULL);
}

void ui_The_B_screen_destroy(void)
{
    if(ui_The_B) lv_obj_del(ui_The_B);

    ui_The_B = NULL;
    ui_Mune = NULL;
    ui_Step = NULL;
    ui_Weather = NULL;
    ui_Music = NULL;
    ui_Notebook = NULL;
    ui_Caculator = NULL;
    ui_Heart_Detect = NULL;
    ui_Compass = NULL;
    ui_SettingApp = NULL;
    ui_News = NULL;
    ui_Clock = NULL;
}
