// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#include "ui.h"

#define UI_THE_C_PANEL_HEIGHT 420
#define UI_THE_C_OPEN_ANIM_MS 55
#define UI_THE_C_CLOSE_ANIM_MS 45
#define UI_THE_C_TRIGGER_ZONE_HEIGHT 58
#define UI_THE_C_TRIGGER_MIN_DRAG 50
#define UI_THE_C_TRIGGER_MAX_DRAG 150
#define UI_THE_C_CLOSE_MIN_DRAG 40

static lv_obj_t *ui_The_C_trigger_zone = NULL;
static lv_obj_t *ui_The_C_close_zone = NULL;
static bool ui_the_c_open = false;
static bool ui_the_c_tracking = false;
static bool ui_the_c_close_tracking = false;
static lv_point_t ui_the_c_press_point = {0, 0};
static lv_point_t ui_the_c_close_start_point = {0, 0};

lv_obj_t * ui_The_C = NULL;
lv_obj_t * ui_Configure_Panel = NULL;
lv_obj_t * ui_WIFI = NULL;
lv_obj_t * ui_BulueTooth = NULL;
lv_obj_t * ui_Setting = NULL;
lv_obj_t * ui_Speak_Low = NULL;
lv_obj_t * ui_Mute = NULL;
lv_obj_t * ui_Speak_Loud = NULL;
lv_obj_t * ui_Music_Panel = NULL;
lv_obj_t * ui_Next1 = NULL;
lv_obj_t * ui_STOP = NULL;
lv_obj_t * ui_Next = NULL;
lv_obj_t * ui_Cycle = NULL;
lv_obj_t * ui_Cycle2 = NULL;

static void ui_the_c_trigger_event(lv_event_t *e);

static void ui_the_c_apply_cn_font(lv_obj_t *obj, bool compact)
{
    (void)compact;
    lv_obj_set_style_text_font(obj, &lv_font_simsun_16_cjk, 0);
}

static void ui_the_c_prepare_box(lv_obj_t *obj)
{
    lv_obj_remove_style_all(obj);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
}

static void ui_the_c_set_y(void *obj, int32_t value)
{
    lv_obj_set_y((lv_obj_t *)obj, value);
}

static void ui_the_c_anim_finish(lv_anim_t *anim)
{
    LV_UNUSED(anim);
    if(!ui_the_c_open) {
        if(ui_The_C) {
            lv_obj_add_flag(ui_The_C, LV_OBJ_FLAG_HIDDEN);
        }
        if(ui_The_C_close_zone) {
            lv_obj_add_flag(ui_The_C_close_zone, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void ui_the_c_set_event_bubble(lv_obj_t *obj)
{
    if(obj == NULL) {
        return;
    }

    lv_obj_add_flag(obj, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_GESTURE_BUBBLE);
}

static void ui_the_c_start_anim(lv_coord_t target_y, uint32_t duration)
{
    if(ui_The_C == NULL) {
        return;
    }

    lv_anim_del(ui_The_C, ui_the_c_set_y);
    lv_obj_clear_flag(ui_The_C, LV_OBJ_FLAG_HIDDEN);

    lv_anim_t anim;
    lv_anim_init(&anim);
    lv_anim_set_var(&anim, ui_The_C);
    lv_anim_set_exec_cb(&anim, ui_the_c_set_y);
    lv_anim_set_values(&anim, lv_obj_get_y(ui_The_C), target_y);
    lv_anim_set_time(&anim, duration);
    lv_anim_set_path_cb(&anim, lv_anim_path_linear);
    lv_anim_set_ready_cb(&anim, ui_the_c_anim_finish);
    lv_anim_start(&anim);
}

static lv_obj_t *ui_the_c_create_tile(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, const char *symbol, const char *label_text, lv_color_t bg)
{
    lv_obj_t *tile = lv_obj_create(parent);
    ui_the_c_prepare_box(tile);
    lv_obj_set_size(tile, 92, 72);
    lv_obj_set_pos(tile, x, y);
    lv_obj_set_style_radius(tile, 24, 0);
    lv_obj_set_style_bg_color(tile, bg, 0);
    lv_obj_set_style_bg_opa(tile, LV_OPA_COVER, 0);
    lv_obj_add_flag(tile, LV_OBJ_FLAG_CLICKABLE);
    ui_the_c_set_event_bubble(tile);

    lv_obj_t *icon = lv_label_create(tile);
    lv_label_set_text(icon, symbol);
    lv_obj_center(icon);
    lv_obj_set_y(icon, -10);
    lv_obj_set_style_text_font(icon, &lv_font_montserrat_16, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(0xFFFFFF), 0);
    ui_the_c_set_event_bubble(icon);

    lv_obj_t *title = lv_label_create(tile);
    lv_label_set_text(title, label_text);
    lv_obj_align(title, LV_ALIGN_BOTTOM_MID, 0, -6);
    ui_the_c_apply_cn_font(title, true);
    lv_obj_set_style_text_color(title, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_text_opa(title, LV_OPA_80, 0);
    ui_the_c_set_event_bubble(title);

    return tile;
}

static lv_obj_t *ui_the_c_create_control_btn(lv_obj_t *parent, lv_coord_t x, const char *symbol, lv_coord_t w)
{
    lv_obj_t *btn = lv_obj_create(parent);
    ui_the_c_prepare_box(btn);
    lv_obj_set_size(btn, w, 60);
    lv_obj_set_pos(btn, x, 34);
    lv_obj_set_style_radius(btn, 24, 0);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x15181D), 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_add_flag(btn, LV_OBJ_FLAG_CLICKABLE);
    ui_the_c_set_event_bubble(btn);

    lv_obj_t *label = lv_label_create(btn);
    lv_label_set_text(label, symbol);
    lv_obj_center(label);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_16, 0);
    lv_obj_set_style_text_color(label, lv_color_hex(0xF5F7FA), 0);
    ui_the_c_set_event_bubble(label);

    return btn;
}

static void ui_the_c_close_event(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(!ui_the_c_open) {
        if(code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
            ui_the_c_close_tracking = false;
        }
        return;
    }

    lv_indev_t *indev = lv_indev_get_act();
    if(code == LV_EVENT_GESTURE) {
        if(indev && lv_indev_get_gesture_dir(indev) == LV_DIR_TOP) {
            ui_the_c_close_tracking = false;
            lv_indev_wait_release(indev);
            ui_The_C_hide();
        }
        return;
    }

    if(indev == NULL) {
        return;
    }

    if(code == LV_EVENT_PRESSED) {
        lv_indev_get_point(indev, &ui_the_c_close_start_point);
        ui_the_c_close_tracking = true;
        return;
    }

    if(code == LV_EVENT_PRESSING && ui_the_c_close_tracking) {
        lv_point_t point;
        lv_indev_get_point(indev, &point);

        int32_t dx = point.x - ui_the_c_close_start_point.x;
        int32_t dy = point.y - ui_the_c_close_start_point.y;
        if(dy <= -UI_THE_C_CLOSE_MIN_DRAG && LV_ABS(dx) < ((-dy) / 2 + 16)) {
            ui_the_c_close_tracking = false;
            lv_indev_wait_release(indev);
            ui_The_C_hide();
        }
        return;
    }

    if(code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
        ui_the_c_close_tracking = false;
    }
}

static void ui_the_c_bind_close_target(lv_obj_t *obj)
{
    if(obj == NULL) {
        return;
    }

    lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
    ui_the_c_set_event_bubble(obj);
    lv_obj_add_event_cb(obj, ui_the_c_close_event, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_close_event, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_close_event, LV_EVENT_RELEASED, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_close_event, LV_EVENT_PRESS_LOST, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_close_event, LV_EVENT_GESTURE, NULL);
}

static void ui_the_c_bind_trigger_target(lv_obj_t *obj)
{
    if(obj == NULL) {
        return;
    }

    lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(obj, ui_the_c_trigger_event, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_trigger_event, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_trigger_event, LV_EVENT_RELEASED, NULL);
    lv_obj_add_event_cb(obj, ui_the_c_trigger_event, LV_EVENT_PRESS_LOST, NULL);
}

static void ui_the_c_trigger_event(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_get_act();
    if(indev == NULL) {
        return;
    }

    if(code == LV_EVENT_PRESSED) {
        if(ui_the_c_open) {
            ui_the_c_tracking = false;
            return;
        }

        lv_indev_get_point(indev, &ui_the_c_press_point);
        ui_the_c_tracking = true;
        return;
    }

    if(code == LV_EVENT_PRESSING && ui_the_c_tracking && !ui_the_c_open) {
        lv_point_t point;
        lv_indev_get_point(indev, &point);

        int32_t dx = point.x - ui_the_c_press_point.x;
        int32_t dy = point.y - ui_the_c_press_point.y;
        if(dy >= UI_THE_C_TRIGGER_MIN_DRAG && dy <= UI_THE_C_TRIGGER_MAX_DRAG && LV_ABS(dx) < (dy / 2 + 12)) {
            ui_the_c_tracking = false;
            lv_indev_wait_release(indev);
            ui_The_C_show();
        }
        return;
    }

    if(code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
        ui_the_c_tracking = false;
    }
}

void ui_The_C_show(void)
{
    if(ui_The_C == NULL || ui_the_c_open) {
        return;
    }

    ui_the_c_open = true;
    ui_the_c_tracking = false;
    ui_the_c_close_tracking = false;
    if(ui_The_C_trigger_zone) {
        lv_obj_add_flag(ui_The_C_trigger_zone, LV_OBJ_FLAG_HIDDEN);
    }
    if(ui_The_C_close_zone) {
        lv_obj_clear_flag(ui_The_C_close_zone, LV_OBJ_FLAG_HIDDEN);
    }
    ui_the_c_start_anim(0, UI_THE_C_OPEN_ANIM_MS);
}

void ui_The_C_hide(void)
{
    if(ui_The_C == NULL || !ui_the_c_open) {
        return;
    }

    ui_the_c_open = false;
    ui_the_c_tracking = false;
    ui_the_c_close_tracking = false;
    if(ui_The_C_trigger_zone) {
        lv_obj_clear_flag(ui_The_C_trigger_zone, LV_OBJ_FLAG_HIDDEN);
    }
    ui_the_c_start_anim(-UI_THE_C_PANEL_HEIGHT, UI_THE_C_CLOSE_ANIM_MS);
}

void ui_The_C_toggle(void)
{
    if(ui_the_c_open) {
        ui_The_C_hide();
    } else {
        ui_The_C_show();
    }
}

bool ui_The_C_is_open(void)
{
    return ui_the_c_open;
}

void ui_The_C_screen_init(void)
{
    if(ui_The_C != NULL) {
        return;
    }

    ui_The_C_trigger_zone = lv_obj_create(lv_layer_top());
    ui_the_c_prepare_box(ui_The_C_trigger_zone);
    lv_obj_set_size(ui_The_C_trigger_zone, LV_HOR_RES, UI_THE_C_TRIGGER_ZONE_HEIGHT);
    lv_obj_align(ui_The_C_trigger_zone, LV_ALIGN_TOP_MID, 0, 0);
    lv_obj_set_style_bg_opa(ui_The_C_trigger_zone, LV_OPA_TRANSP, 0);
    ui_the_c_bind_trigger_target(ui_The_C_trigger_zone);

    ui_The_C_close_zone = lv_obj_create(lv_layer_top());
    ui_the_c_prepare_box(ui_The_C_close_zone);
    lv_obj_set_size(ui_The_C_close_zone, LV_HOR_RES, LV_VER_RES - UI_THE_C_PANEL_HEIGHT);
    lv_obj_set_pos(ui_The_C_close_zone, 0, UI_THE_C_PANEL_HEIGHT);
    lv_obj_set_style_bg_opa(ui_The_C_close_zone, LV_OPA_TRANSP, 0);
    lv_obj_add_flag(ui_The_C_close_zone, LV_OBJ_FLAG_HIDDEN);
    ui_the_c_bind_close_target(ui_The_C_close_zone);

    ui_The_C = lv_obj_create(lv_layer_top());
    ui_the_c_prepare_box(ui_The_C);
    lv_obj_set_size(ui_The_C, LV_HOR_RES, UI_THE_C_PANEL_HEIGHT);
    lv_obj_set_pos(ui_The_C, 0, -UI_THE_C_PANEL_HEIGHT);
    lv_obj_add_flag(ui_The_C, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_The_C, lv_color_hex(0x050608), 0);
    lv_obj_set_style_bg_opa(ui_The_C, LV_OPA_COVER, 0);
    ui_the_c_bind_close_target(ui_The_C);

    ui_Configure_Panel = lv_obj_create(ui_The_C);
    ui_the_c_prepare_box(ui_Configure_Panel);
    lv_obj_set_size(ui_Configure_Panel, 336, 196);
    lv_obj_align(ui_Configure_Panel, LV_ALIGN_TOP_MID, 0, 18);
    lv_obj_set_style_radius(ui_Configure_Panel, 28, 0);
    lv_obj_set_style_bg_color(ui_Configure_Panel, lv_color_hex(0x0B1016), 0);
    lv_obj_set_style_bg_opa(ui_Configure_Panel, LV_OPA_COVER, 0);
    lv_obj_add_flag(ui_Configure_Panel, LV_OBJ_FLAG_CLICKABLE);
    ui_the_c_set_event_bubble(ui_Configure_Panel);

    ui_WIFI = ui_the_c_create_tile(ui_Configure_Panel, 18, 18, LV_SYMBOL_WIFI, "WIFI", lv_color_hex(0x3A4656));
    ui_BulueTooth = ui_the_c_create_tile(ui_Configure_Panel, 122, 18, LV_SYMBOL_BLUETOOTH, "BT", lv_color_hex(0x3A4656));
    ui_Setting = ui_the_c_create_tile(ui_Configure_Panel, 226, 18, LV_SYMBOL_SETTINGS, "SET", lv_color_hex(0x3A4656));
    ui_Speak_Low = ui_the_c_create_tile(ui_Configure_Panel, 18, 106, LV_SYMBOL_VOLUME_MID, "低音", lv_color_hex(0x3A4656));
    ui_Mute = ui_the_c_create_tile(ui_Configure_Panel, 122, 106, LV_SYMBOL_MUTE, "静音", lv_color_hex(0x3A4656));
    ui_Speak_Loud = ui_the_c_create_tile(ui_Configure_Panel, 226, 106, LV_SYMBOL_VOLUME_MAX, "高音", lv_color_hex(0x3A4656));

    ui_Music_Panel = lv_obj_create(ui_The_C);
    ui_the_c_prepare_box(ui_Music_Panel);
    lv_obj_set_size(ui_Music_Panel, 272, 162);
    lv_obj_align(ui_Music_Panel, LV_ALIGN_TOP_MID, 0, 242);
    lv_obj_set_style_radius(ui_Music_Panel, 34, 0);
    lv_obj_set_style_bg_color(ui_Music_Panel, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(ui_Music_Panel, LV_OPA_COVER, 0);
    lv_obj_add_flag(ui_Music_Panel, LV_OBJ_FLAG_CLICKABLE);
    ui_the_c_set_event_bubble(ui_Music_Panel);

    // lv_obj_t *music_title = lv_label_create(ui_Music_Panel);
    // // lv_label_set_text(music_title, "Music");
    // lv_obj_align(music_title, LV_ALIGN_TOP_LEFT, 20, 14);
    // ui_the_c_apply_cn_font(music_title, false);
    // lv_obj_set_style_text_color(music_title, lv_color_hex(0x3A4656), 0);
    // ui_the_c_set_event_bubble(music_title);

    // lv_obj_t *music_desc = lv_label_create(ui_Music_Panel);
    // // lv_label_set_text(music_desc, "任意上划收起");
    // lv_obj_align(music_desc, LV_ALIGN_TOP_LEFT, 20, 38);
    // ui_the_c_apply_cn_font(music_desc, true);
    // lv_obj_set_style_text_color(music_desc, lv_color_hex(0x3A4656), 0);
    // ui_the_c_set_event_bubble(music_desc);

    ui_Next1 = ui_the_c_create_control_btn(ui_Music_Panel, 18, LV_SYMBOL_PREV, 70);
    ui_STOP = ui_the_c_create_control_btn(ui_Music_Panel, 101, LV_SYMBOL_PLAY, 70);
    ui_Next = ui_the_c_create_control_btn(ui_Music_Panel, 184, LV_SYMBOL_NEXT, 70);
    ui_Cycle = ui_the_c_create_control_btn(ui_Music_Panel, 58, LV_SYMBOL_LOOP, 64);
    lv_obj_set_y(ui_Cycle, 100);
    ui_Cycle2 = ui_the_c_create_control_btn(ui_Music_Panel, 150, LV_SYMBOL_REFRESH, 64);
    lv_obj_set_y(ui_Cycle2, 100);

    ui_the_c_open = false;
    ui_the_c_tracking = false;
}

void ui_The_C_screen_destroy(void)
{
    if(ui_The_C_trigger_zone) {
        lv_obj_del(ui_The_C_trigger_zone);
    }
    if(ui_The_C_close_zone) {
        lv_obj_del(ui_The_C_close_zone);
    }
    if(ui_The_C) {
        lv_obj_del(ui_The_C);
    }

    ui_The_C_trigger_zone = NULL;
    ui_The_C_close_zone = NULL;
    ui_The_C = NULL;
    ui_Configure_Panel = NULL;
    ui_WIFI = NULL;
    ui_BulueTooth = NULL;
    ui_Setting = NULL;
    ui_Speak_Low = NULL;
    ui_Mute = NULL;
    ui_Speak_Loud = NULL;
    ui_Music_Panel = NULL;
    ui_Next1 = NULL;
    ui_STOP = NULL;
    ui_Next = NULL;
    ui_Cycle = NULL;
    ui_Cycle2 = NULL;
    ui_the_c_open = false;
    ui_the_c_tracking = false;
    ui_the_c_close_tracking = false;
    ui_the_c_press_point.x = 0;
    ui_the_c_press_point.y = 0;
    ui_the_c_close_start_point.x = 0;
    ui_the_c_close_start_point.y = 0;
}
