// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#ifndef UI_THE_C_H
#define UI_THE_C_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_The_C
extern void ui_The_C_screen_init(void);
extern void ui_The_C_screen_destroy(void);
extern lv_obj_t * ui_The_C;
extern lv_obj_t * ui_Configure_Panel;
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_BulueTooth;
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_Speak_Low;
extern lv_obj_t * ui_Mute;
extern lv_obj_t * ui_Speak_Loud;
extern lv_obj_t * ui_Music_Panel;
extern lv_obj_t * ui_Next1;
extern lv_obj_t * ui_STOP;
extern lv_obj_t * ui_Next;
extern lv_obj_t * ui_Cycle;
extern lv_obj_t * ui_Cycle2;

extern void ui_The_C_show(void);
extern void ui_The_C_hide(void);
extern void ui_The_C_toggle(void);
extern bool ui_The_C_is_open(void);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
