// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#include "ui.h"

lv_obj_t * ui_The_D = NULL;
lv_obj_t * ui_TIME1 = NULL;
// event funtions
void ui_event_The_D(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_get_act();

    if(event_code != LV_EVENT_GESTURE || indev == NULL) {
        return;
    }

    lv_dir_t dir = lv_indev_get_gesture_dir(indev);
    if(dir == LV_DIR_TOP && ui_The_C_is_open()) {
        lv_indev_wait_release(indev);
        ui_The_C_hide();
        return;
    }

    if(ui_The_C_is_open()) {
        return;
    }

    if(dir == LV_DIR_LEFT) {
        lv_indev_wait_release(indev);
        _ui_screen_change(&ui_The_E, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_The_E_screen_init);
    }
    if(dir == LV_DIR_RIGHT) {
        lv_indev_wait_release(indev);
        _ui_screen_change(&ui_The_B, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_The_B_screen_init);
    }
}

// build funtions

void ui_The_D_screen_init(void)
{
    ui_The_D = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_The_D, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_The_D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_The_D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME1 = lv_label_create(ui_The_D);
    lv_obj_set_width(ui_TIME1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_TIME1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_TIME1, -7);
    lv_obj_set_y(ui_TIME1, -50);
    lv_obj_set_align(ui_TIME1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIME1, "D");
    lv_obj_set_style_text_color(ui_TIME1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TIME1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TIME1, &ui_font_TIME4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_The_D, ui_event_The_D, LV_EVENT_ALL, NULL);

}

void ui_The_D_screen_destroy(void)
{
    if(ui_The_D) lv_obj_del(ui_The_D);

    // NULL screen variables
    ui_The_D = NULL;
    ui_TIME1 = NULL;

}
