// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#ifndef UI_THE_B_H
#define UI_THE_B_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_The_B
extern void ui_The_B_screen_init(void);
extern void ui_The_B_screen_destroy(void);
extern void ui_event_The_B(lv_event_t * e);
extern lv_obj_t * ui_The_B;
extern lv_obj_t * ui_Mune;
extern lv_obj_t * ui_Step;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Music;
extern lv_obj_t * ui_Notebook;
extern lv_obj_t * ui_Caculator;
extern lv_obj_t * ui_Heart_Detect;
extern lv_obj_t * ui_Compass;
extern lv_obj_t * ui_SettingApp;
extern lv_obj_t * ui_News;
extern lv_obj_t * ui_Clock;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

