// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#ifndef UI_THE_D_H
#define UI_THE_D_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_The_D
extern void ui_The_D_screen_init(void);
extern void ui_The_D_screen_destroy(void);
extern void ui_event_The_D(lv_event_t * e);
extern lv_obj_t * ui_The_D;
extern lv_obj_t * ui_TIME1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

