// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AMOLED

#ifndef UI_THE_E_H
#define UI_THE_E_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_The_E
extern void ui_The_E_screen_init(void);
extern void ui_The_E_screen_destroy(void);
extern void ui_event_The_E(lv_event_t * e);
extern lv_obj_t * ui_The_E;
extern lv_obj_t * ui_TIME2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

